// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: acd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   string `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	AgentId string `protobuf:"bytes,2,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
}

func (x *RequestAgentState) Reset() {
	*x = RequestAgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAgentState) ProtoMessage() {}

func (x *RequestAgentState) ProtoReflect() protoreflect.Message {
	mi := &file_acd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAgentState.ProtoReflect.Descriptor instead.
func (*RequestAgentState) Descriptor() ([]byte, []int) {
	return file_acd_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAgentState) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RequestAgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ResponseAgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   string `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	AgentId string `protobuf:"bytes,2,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
	State   uint32 `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *ResponseAgentState) Reset() {
	*x = ResponseAgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAgentState) ProtoMessage() {}

func (x *ResponseAgentState) ProtoReflect() protoreflect.Message {
	mi := &file_acd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAgentState.ProtoReflect.Descriptor instead.
func (*ResponseAgentState) Descriptor() ([]byte, []int) {
	return file_acd_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAgentState) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ResponseAgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ResponseAgentState) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_acd_proto protoreflect.FileDescriptor

var file_acd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x63, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x43, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x32, 0x49, 0x0a, 0x0a, 0x41, 0x43, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_acd_proto_rawDescOnce sync.Once
	file_acd_proto_rawDescData = file_acd_proto_rawDesc
)

func file_acd_proto_rawDescGZIP() []byte {
	file_acd_proto_rawDescOnce.Do(func() {
		file_acd_proto_rawDescData = protoimpl.X.CompressGZIP(file_acd_proto_rawDescData)
	})
	return file_acd_proto_rawDescData
}

var file_acd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acd_proto_goTypes = []interface{}{
	(*RequestAgentState)(nil),  // 0: pb.RequestAgentState
	(*ResponseAgentState)(nil), // 1: pb.ResponseAgentState
}
var file_acd_proto_depIdxs = []int32{
	0, // 0: pb.ACDService.AgentState:input_type -> pb.RequestAgentState
	1, // 1: pb.ACDService.AgentState:output_type -> pb.ResponseAgentState
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acd_proto_init() }
func file_acd_proto_init() {
	if File_acd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acd_proto_goTypes,
		DependencyIndexes: file_acd_proto_depIdxs,
		MessageInfos:      file_acd_proto_msgTypes,
	}.Build()
	File_acd_proto = out.File
	file_acd_proto_rawDesc = nil
	file_acd_proto_goTypes = nil
	file_acd_proto_depIdxs = nil
}
